#include <stdlib.h> 
#include <stdio.h> 


void func(){ 

    char qnjjsv = 48;
    char cqnfwo = 2;
    char xffpcp = 100;
    char orznaz = 101;
    char shklfh = 109;
    char ssqiio = 66;
    char iodosp = 67;
    char olnxbg = 58;
    char tskqba = 48;
    char tshsiq = 59;
    char osanwc = 60;
    char tumvxo = 110;
    char nahyzz = 99;
    char zeoezi = 32;
    char zzovxd = 76;
    char qlevmk = 47;
    char zseykh = 68;
    char jxxifn = 56;
    char sqwztv = 35;
    char epkuyu = 106;
    char ywpuwa = 26;
    char lwqbxm = 95;
    char fsrjhp = 104;
    char tbgirm = 66;
    char qlqlkz = 65;
    char kwcntw = 7;
    char dogcuk = 61;
    char vefqbx = 98;
    char jmnveo = 24;
    char kuwtyi = 115;
    char ydmpna = 2;
    char vndyfp = 78;
    char rqxklt = 57;
    char cvizez = 46;
    char ksalnm = 60;
    char cydboi = 20;
    char gjlyjq = 8;
    char qztimg = 5;
    char wdtxlm = 32;
    char wpclja = 98;
    char wodefj = 112;
    char zwhasf = 78;
    char kvxsek = 92;
    char klxhcc = 66;
    char knvnwn = 3;
    char seoyce = 88;
    char pgoftg = 28;
    char rkrbmm = 90;
    char pftdto = 112;
    char kuyaqo = 10;
    char fayefd = 97;
    char nrcvez = 64;
    char xozsnq = 110;
    char alnjec = 115;
    char lrhynk = 49;
    char wtxfrl = 73;
    char sqgwgi = 29;
    char yupteo = 24;
    char yvlzfb = 54;
    char duohdb = 65;
    char jqvmhx = 33;
    char zivuje = 20;
    char frhmen = 73;
    char xdesoz = 113;
    char kntqtd = 91;
    char obvyvr = 2;
    char xtreoh = 53;
    char cglxdj = 117;
    char yhhreh = 84;
    char yvkmlx = 2;
    char xojjib = 68;
    char whyarl = 85;
    char fwkzdp = 55;
    char pqgncw = 118;
    char uqizfc = 59;
    char odcbqc = 97;
    char oxsejn = 108;
    char vcxqtb = 111;
    char aqkaku = 106;
    char deuhvu = 110;
    char wmptyr = 26;
    char sfznoi = 89;
    char veclcf = 55;
    char ercvkl = 64;
    char fzvwul = 8;
    char rzujeo = 56;
    char dxvzxj = 86;
    char xhumie = 107;
    char kkguxo = 28;
    char ofleta = 1;
    char upsprq = 53;
    char foqzmf = 107;
    char nfjwus = 8;
    char uqpesj = 30;
    char tdswav = 113;
    char xnsbpr = 34;
    char ukdnkf = 47;
    char khqgti = 0;
    char vzdtbp = 102;
    char skunfg = 82;
    char crwhpb = 36;
    char tmizhc = 9;
    char orkmqi = 75;
    char vhcglr = 72;
    char laogvy = 7;
    char jizjjp = 42;
    char wwxwqh = 15;
    char icuzrt = 44;
    char lrtepi = 118;
    char tsgqrp = 98;
    char leyitk = 76;
    char aptecx = 69;
    char kvbdul = 95;
    char qdnhrk = 26;
    char kylrtw = 60;
    char pidkpv = 18;
    char pjecpv = 2;
    char amonhr = 6;
    char jvrwae = 56;
    char sujdyd = 94;
    char swbwgd = 49;
    char nywntn = 97;
    char rcvubj = 16;
    char lsxfzz = 78;
    char osizgc = 52;
    char mnjxgq = 50;
    char rkzmmf = 77;
    char ivdaus = 93;
    ivdaus++;
    rkzmmf++;
    mnjxgq++;
    osizgc++;
    lsxfzz++;
    rcvubj++;
    nywntn++;
    swbwgd++;
    sujdyd++;
    jvrwae++;
    amonhr++;
    pjecpv++;
    pidkpv++;
    kylrtw++;
    qdnhrk++;
    kvbdul++;
    aptecx++;
    leyitk++;
    tsgqrp++;
    lrtepi++;
    icuzrt++;
    wwxwqh++;
    jizjjp++;
    laogvy++;
    vhcglr++;
    orkmqi++;
    tmizhc++;
    crwhpb++;
    skunfg++;
    vzdtbp++;
    khqgti++;
    ukdnkf++;
    xnsbpr++;
    tdswav++;
    uqpesj++;
    nfjwus++;
    foqzmf++;
    upsprq++;
    ofleta++;
    kkguxo++;
    xhumie++;
    dxvzxj++;
    rzujeo++;
    fzvwul++;
    ercvkl++;
    veclcf++;
    sfznoi++;
    wmptyr++;
    deuhvu++;
    aqkaku++;
    vcxqtb++;
    oxsejn++;
    odcbqc++;
    uqizfc++;
    pqgncw++;
    fwkzdp++;
    whyarl++;
    xojjib++;
    yvkmlx++;
    yhhreh++;
    cglxdj++;
    xtreoh++;
    obvyvr++;
    kntqtd++;
    xdesoz++;
    frhmen++;
    zivuje++;
    jqvmhx++;
    duohdb++;
    yvlzfb++;
    yupteo++;
    sqgwgi++;
    wtxfrl++;
    lrhynk++;
    alnjec++;
    xozsnq++;
    nrcvez++;
    fayefd++;
    kuyaqo++;
    pftdto++;
    rkrbmm++;
    pgoftg++;
    seoyce++;
    knvnwn++;
    klxhcc++;
    kvxsek++;
    zwhasf++;
    wodefj++;
    wpclja++;
    wdtxlm++;
    qztimg++;
    gjlyjq++;
    cydboi++;
    ksalnm++;
    cvizez++;
    rqxklt++;
    vndyfp++;
    ydmpna++;
    kuwtyi++;
    jmnveo++;
    vefqbx++;
    dogcuk++;
    kwcntw++;
    qlqlkz++;
    tbgirm++;
    fsrjhp++;
    lwqbxm++;
    ywpuwa++;
    epkuyu++;
    sqwztv++;
    jxxifn++;
    zseykh++;
    qlevmk++;
    zzovxd++;
    zeoezi++;
    nahyzz++;
    tumvxo++;
    osanwc++;
    tshsiq++;
    tskqba++;
    olnxbg++;
    iodosp++;
    ssqiio++;
    shklfh++;
    orznaz++;
    xffpcp++;
    cqnfwo++;
    qnjjsv++;
      
     
} 

int main(int argc, char* argv[]) {
 
  func(); 
} 
